main: pl.daneu.simpledrop.SimpleDrop
name: SimpleDrop
version: 1.0
api-version: 1.17
author: Daneu
description: Prosty plugin na drop :3

commands:
  drop:

permissions:
  simpledrop.*:
    description: Wszystkie permisje w jednej
    default: op
    children:
      - simpledrop.bonusdrop
  simpledrop.bonusdrop:
    description: Bonusowy drop dla graczy z permisja
    default: op